export const categoryKeywords: Record<string, string[]> = {
  "🍎 Alimentari": [
    "latte", "uova", "pane", "burro", "formaggio", "yogurt", "frutta", "verdura",
    "carne", "pesce", "pasta", "riso", "olio", "sale", "zucchero", "caffè",
    "acqua", "succo", "bibita", "birra", "vino", "cereali", "biscotti", "cioccolato",
    "gelato", "pizza", "hamburger", "pollo", "manzo", "maiale", "tonno", "salmone",
    "prosciutto", "salame", "mortadella", "parmigiano", "mozzarella", "ricotta",
    "panna", "pomodoro", "insalata", "carota", "patata", "cipolla", "aglio",
    "peperone", "zucchina", "melanzana", "finocchio", "sedano", "spinaci",
    "broccoli", "cavolfiore", "fagioli", "lenticchie", "ceci", "piselli",
    "mais", "patatine", "popcorn", "noci", "mandorle", "pistacchi",
    "miele", "marmellata", "nutella", "burro arachidi", "cereali", "fiocchi",
    "latte vegetale", "tofu", "tempeh", "seitan", "hummus", "guacamole",
    "salsa", "ketchup", "maionese", "senape", "aceto", "limone", "arancia",
    "mela", "banana", "pera", "pesca", "albicocca", "ciliegia", "fragola",
    "mirtillo", "lamponi", "uva", "anguria", "melone", "ananas", "kiwi",
    "mango", "papaya", "cocco", "avocado", "olive", "capperi", "acciughe",
    "sgombro", "sardine", "gamberi", "cozze", "vongole", "calamari", "polpo",
    "risotto", "lasagna", "ravioli", "tortellini", "gnocchi", "polenta",
    "purè", "patatine fritte", "crocchette", "bastoncini", "cotoletta",
    "arrosto", "stufato", "spezzatino", "ragù", "carbonara", "amatriciana",
    "pesto", "ragù", "besciamella", "parmigiana", "caprese", "bruschetta",
    "focaccia", "piadina", "crostini", "taralli", "grissini", "crackers",
    "fette biscottate", "cornetti", "brioche", "croissant", "muffin",
    "torta", "crostata", "tiramisù", "panna cotta", "budino", "crema",
    "gelato", "sorbetto", "granita", "ghiacciolo", "yogurt greco", "kefir",
    "latte mandorla", "latte soia", "latte avena", "latte riso", "latte cocco",
  ],
  "👕 Abbigliamento": [
    "maglietta", "t-shirt", "camicia", "polo", "felpa", "maglione", "cardigan",
    "giacca", "cappotto", "piumino", "gilet", "pantaloni", "jeans", "chinos",
    "bermuda", "shorts", "gonna", "vestito", "abito", "tuta", "completo",
    "calzini", "calze", "collant", "mutande", "boxer", "slip", "reggiseno",
    "top", "canotta", "body", "pigiama", "camicia da notte", "vestaglia",
    "accappatoio", "costume", "bikini", "boxer mare", "ciabatte", "infradito",
    "sandali", "scarpe", "sneakers", "stivali", "stivaletti", "mocassini",
    "ballerine", "décolleté", "tacco", "zoccoli", "pantofole", "calzature",
    "cintura", "brettelle", "cappello", "berretto", "basco", "copricapo",
    "sciarpa", "foulard", "guanti", "guanti touch", "occhiali", "occhiali sole",
    "orologio", "bracciale", "collana", "anello", "orecchini", "gioielli",
    "borsa", "zaino", "valigia", "trolley", "beauty case", "portafoglio",
    "portamonete", "portachiavi", "ombrello", "impermeabile", "mantella",
    "poncho", "k-way", "giacca vento", "pile", "pile polare", "softshell",
    "hardshell", "piumino leggero", "giacca jeans", "giacca pelle", "trench",
    "montgomery", "duffle coat", "peacoat", "parkas", "anorak", "cappa",
  ],
  "🪥 Toilette": [
    "spazzolino", "dentifricio", "shampoo", "bagnoschiuma", "docciaschiuma",
    "sapone", "sapone liquido", "deodorante", "antitraspirante", "rasoio",
    "lametta", "schiuma da barba", "gel da barba", "aftershave", "crema viso",
    "crema corpo", "crema mani", "crema piedi", "latte corpo", "olio corpo",
    "burro corpo", "scrub", "esfoliante", "maschera viso", "maschera capelli",
    "balsamo", "conditioner", "maschera", "olio capelli", "siero capelli",
    "spray capelli", "lacca", "gel", "cera", "pasta modellante", "phon",
    "piastra", "arricciacapelli", "spazzola", "pettine", "pinze", "elastici",
    "mollette", "cerchietto", "fascia", "fazzoletti", "salviette", "carta igienica",
    "assorbenti", "tamponi", "coppetta", "mutande mestruali", "salvaslip",
    "cotone", "dischetti", "bastoncini", "forbicine", "pinzetta", "specchio",
    "lima", "tronchesina", "smalto", "solvente", "base", "top coat", "curativo",
    "crema cuticole", "olio cuticole", "sbiancante", "collutorio", "filo interdentale",
    "scovolino", "idropulsore", "spazzolino elettrico", "testina", "dentifricio bambini",
    "spazzolino bambini", "shampoo bambini", "bagnetto", "crema pannolino",
    "salviette bambini", "pannolini", "mutandine addestramento", "vasino",
    "riduttore", "termometro", "aspiratore nasale", "soluzione fisiologica",
    "garze", "cerotti", "disinfettante", "arnica", "crema scottature", "aloe vera",
    "repellente", "punture", "pomata", "crema contusioni", "gel gambe",
    "calze riposo", "plantari", "solette", "talloniere", "separadita",
  ],
  "💊 Farmacia": [
    "paracetamolo", "ibuprofene", "aspirina", "tachipirina", "moment", "oki",
    "brufen", "nurofen", "antidolorifico", "antinfiammatorio", "antipiretico",
    "cerotti", "cerotto", "garza", "benda", "disinfettante", "betadine",
    "amuchina", "alcol", "acqua ossigenata", "merciocromo", "eurax", "fenistil",
    "antistaminico", "zirtec", "reactine", "aerius", "claritin", "cortisone",
    "bentelan", "deltacortene", "antistaminico crema", "cortisone crema",
    "antidiarroico", "imodium", "dissenten", "fermenti lattici", "enterolactis",
    "yacult", "probiotici", "prebiotici", "fibre", "lassativo", "purgante",
    "supposte", "microclisma", "glicerina", "senna", "frangula", "cascara",
    "antiacido", "maalox", "gaviscon", "rennie", "tums", "ranitidina",
    "omeprazolo", "pantoprazolo", "lansoprazolo", "esomeprazolo", "protettore gastrico",
    "antinausea", "plasil", "peridon", "motilium", "viaggi", "cinetosi",
    "travelgum", "xanax", "valium", "lexotan", "tavor", "enri", "ansiololitico",
    "antidepressivo", "prozac", "zoloft", "efexor", "cymbalta", "sertralina",
    "paroxetina", "fluoxetina", "venlafaxina", "duloxetina", "mirtazapina",
    "bupropione", "agomelatina", "vortioxetina", "melatonina", "valeriana",
    "passiflora", "biancospino", "escolzia", "camomilla", "tiglio", "melissa",
    "integratori", "vitamine", "multivitaminico", "vitamina c", "vitamina d",
    "vitamina b12", "ferro", "magnesio", "potassio", "calcio", "zinco",
    "selenio", "omega 3", "olio pesce", "krill", "coenzima q10", "collagene",
    "acido ialuronico", "glucosamina", "condroitina", "msm", "curcuma", "zenzero",
    "echinacea", "propoli", "miele manuka", "pappa reale", "polline", "gelatina reale",
  ],
  "🔌 Tech": [
    "caricatore", "carica", "cavo", "usb", "lightning", "micro usb", "usb-c",
    "power bank", "batteria", "powerbank", "auricolari", "cuffie", "headphones",
    "airpods", "galaxy buds", "pixel buds", "bluetooth", "wireless", "cablate",
    "adattatore", "hub", "dongle", "multipresa", "ciabatta", "prolunga",
    "caricatore auto", "caricatore wireless", "pad wireless", "stand", "supporto",
    "cover", "custodia", "pellicola", "vetro temperato", "protezione schermo",
    "penna", "stylus", "apple pencil", "s pen", "mouse", "tastiera", "trackpad",
    "chiavetta", "usb drive", "pendrive", "hard disk", "ssd", "nas", "cloud",
    "router", "modem", "switch", "access point", "extender", "repeater", "mesh",
    "cavo ethernet", "cavo hdmi", "cavo displayport", "cavo vga", "cavo dvi",
    "adattatore hdmi", "adattatore vga", "adattatore usb", "lettore schede",
    "scheda sd", "scheda microsd", "scheda cf", "scheda xqd", "cfexpress",
    "hard disk esterno", "ssd esterno", "dock", "docking station", "monitor",
    "schermo", "proiettore", "lavagna", "tablet", "ipad", "surface", "kindle",
    "kobo", "ereader", "smartwatch", "fitbit", "garmin", "apple watch",
    "galaxy watch", "activity tracker", "cardiofrequenzimetro", "gps", "ciclomputer",
    "action cam", "gopro", "dji", "insta360", "drone", "controller", "joystick",
    "gamepad", "steam deck", "switch", "playstation", "xbox", "nintendo",
    "vr", "oculus", "quest", "htc vive", "valve index", "psvr", "hololens",
    "stampante", "scanner", "fax", "plotter", "3d printer", "filamento", "resina",
    "raspberry pi", "arduino", "esp32", "esp8266", "microcontrollore", "sensori",
    "attuatori", "relay", "breadboard", "cavi dupont", "resistenze", "led",
    "display", "oled", "lcd", "e-ink", "touchscreen", "tastiera meccanica",
    "switch cherry", "switch gateron", "switch kailh", "keycaps", "keycap",
    "artisan", "wrist rest", "palm rest", "mousepad", "tappetino", "scrivania",
    "sedia", "ergonomica", "gaming", "ufficio", "regolabile", "altezza",
    "monitor arm", "braccio monitor", "supporto laptop", "stand laptop",
    "cooling pad", "ventola", "raffreddamento", "thermal paste", "pasta termica",
    "cpu", "gpu", "ram", "ssd nvme", "ssd sata", "hdd", "motherboard", "scheda madre",
    "case", "chassis", "alimentatore", "psu", "modulare", "semi-modulare",
    "non modulare", "80 plus", "bronze", "silver", "gold", "platinum", "titanium",
    "watercooling", "aio", "custom loop", "radiatore", "pompa", "blocco cpu",
    "blocco gpu", "tubo", "raccordo", "liquido", "refrigerante", "colorato",
    "uv", "rgb", "argb", "addressable", "controller", "hub rgb", "ventole",
    "pwm", "dc", "static pressure", "airflow", "silenzioso", "silent",
    "noctua", "be quiet", "corsair", "nzxt", "fractal", "lian li", "phanteks",
    "cooler master", "thermaltake", "deepcool", "arctic", "scythe", "noctua",
  ],
  "📄 Documenti": [
    "passaporto", "carta identità", "carta d'identità", "patente", "patente guida",
    "tessera sanitaria", "codice fiscale", "tessera elettorale", "libretto pensione",
    "certificato nascita", "certificato matrimonio", "certificato morte",
    "atto notorio", "procura", "delega", "testamento", "contratto", "affitto",
    "compravendita", "mutuo", "prestito", "finanziamento", "assicurazione",
    "rca", "rc auto", "rc famiglia", "rc professionale", "infortuni", "vita",
    "salute", "viaggio", "casa", "condominio", "auto", "moto", "camper",
    "barca", "drone", "bici", "monopattino", "skateboard", "hoverboard",
    "segway", "ninebot", "xiaomi", "ninebot", "segway", "ninebot", "xiaomi",
    "biglietto", "prenotazione", "voucher", "conferma", "ricevuta", "fattura",
    "scontrino", "ricevuta fiscale", "documento trasporto", "ddt", "bolletta",
    "utenze", "luce", "gas", "acqua", "internet", "telefono", "cellulare",
    "abbonamento", "pay tv", "streaming", "netflix", "prime", "disney+",
    "spotify", "apple music", "youtube premium", "google one", "icloud",
    "onedrive", "dropbox", "wetransfer", "gmail", "outlook", "yahoo", "libero",
    "virgilio", "pec", "firma digitale", "spid", "cie", "cns", "firma remota",
    "timestamp", "marca temporale", "blockchain", "notarizzazione", "legalità",
    "compliance", "gdpr", "privacy", "cookie", "consenso", "informativa",
    "termini", "condizioni", "licenza", "copyright", "marchio", "brevetto",
    "modello utilità", "design", "know-how", "segreto industriale", "concorrenza",
    "antitrust", "consumatori", "class action", "risarcimento", "danno",
    "moral", "materiale", "patrimoniale", "non patrimoniale", "biologico",
    "esistenziale", "lavoro", "licenziamento", "dimissioni", "maternità",
    "paternità", "malattia", "infortunio", "ferie", "permessi", "rol", "ex festivi",
    "straordinari", "notturno", "festivo", "domenicale", "turnazione", "reparto",
    "turno", "orario", "flessibile", "smart working", "remote", "ibrid", "presenza",
    "badge", "timbratura", "geolocalizzazione", "gps", "rfid", "nfc", "qr code",
    "barcode", "datamatrix", "pdf417", "aztec", "maxicode", "postnet", "planet",
    "intelligent mail", "rm4scc", "kix", "tnt", "dpd", "gls", "bartolini", "sda",
    "nexive", "poste", "italiane", "poste italiane", "pacco", "pacco celere",
    "pacco ordinario", "posta raccomandata", "posta prioritaria", "posta ordinaria",
    "posta celere", "posta express", "posta internazionale", "ems", "dhl", "ups",
    "fedex", "tnt", "gls", "bartolini", "sda", "nexive", "poste", "italiane",
  ],
};

export function inferCategory(itemName: string, categories: { id: string; name: string; emoji: string }[]): string | null {
  const normalized = itemName.toLowerCase().trim();
  
  for (const [categoryLabel, keywords] of Object.entries(categoryKeywords)) {
    for (const keyword of keywords) {
      if (normalized.includes(keyword.toLowerCase())) {
        const matched = categories.find(c => 
          `${c.emoji} ${c.name}` === categoryLabel || c.name === categoryLabel.replace(/^[^\s]+\s/, '')
        );
        if (matched) return matched.id;
      }
    }
  }
  
  return null;
}